FROM apache/airflow:2.6.0-python3.10

COPY requirements.airflow.txt /
RUN pip install --no-cache-dir -r /requirements.airflow.txt

USER root
RUN mkdir -p /home/airflow/bentoml
RUN chmod -R 775 /home/airflow/bentoml
COPY src /opt/airflow
